# Generated by Django 3.1.5 on 2021-02-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencycal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url_Process',
        ),
    ]
