# Generated by Django 3.1.5 on 2021-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequencycal', '0002_delete_url_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_l', models.URLField(help_text='Enter usl of site')),
                ('words', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
