# Generated by Django 3.1.5 on 2021-02-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencycal', '0003_word_cal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word_cal',
            options={'ordering': ['url_l', 'count']},
        ),
    ]
